/**
 * DB software I use is ORACLE Live SQL
 */

CREATE TABLE PROJECT(  
    PROJECTID VARCHAR(20) NOT NULL,  
    STEP INTEGER NOT NULL,  
    STATUS VARCHAR(5) NOT NULL,  
    PRIMARY KEY(PROJECTID,STEP) 
);

INSERT INTO PROJECT  
VALUES('P100', 0, 'C');

INSERT INTO PROJECT  
VALUES('P100', 1, 'W');

INSERT INTO PROJECT  
VALUES('P100', 2, 'W');

INSERT INTO PROJECT  
VALUES('P201', 0, 'C');

INSERT INTO PROJECT  
VALUES('P201', 1, 'C');

INSERT INTO PROJECT  
VALUES('P333', 0, 'W');

INSERT INTO PROJECT  
VALUES('P333', 1, 'W');

INSERT INTO PROJECT  
VALUES('P333', 2, 'W');

INSERT INTO PROJECT  
VALUES('P333', 3, 'W');

SELECT DISTINCT (PROJECTID) FROM PROJECT 
WHERE STEP = 0 AND STATUS = 'C' 
MINUS 
SELECT DISTINCT(PROJECTID) FROM PROJECT 
WHERE STEP != 0 AND STATUS = 'C';

