/**
 * DB software I use is ORACLE Live SQL
 */

CREATE TABLE PERSONINFO( 
    Name VARCHAR(20) NOT NULL, 
    Address VARCHAR(10) NOT NULL, 
    ID INTEGER NOT NULL, 
    SameFam INTEGER 
);

INSERT INTO PERSONINFO  
VALUES('Alice', 'A', 10, NULL);

INSERT INTO PERSONINFO  
VALUES('Bob', 'B', 15, NULL);

INSERT INTO PERSONINFO  
VALUES('Carmen', 'C', 22, NULL);

INSERT INTO PERSONINFO  
VALUES('Diego', 'A', 9, 10);

INSERT INTO PERSONINFO  
VALUES('Ella', 'B', 3, 15);

INSERT INTO PERSONINFO  
VALUES('Farkhad', 'D', 11, NULL);

DELETE FROM PERSONINFO 
WHERE ID IN( 
    SELECT DISTINCT(S1.ID) 
    FROM PERSONINFO S1, PERSONINFO S2 
    WHERE S1.SameFam IS NULL AND S2.SameFam = S1.ID 
);

SELECT * FROM PERSONINFO;

